package controller;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import kioskapp.ordertransaction.OrderTransaction;

public class OrderTransactionController {

	private DatabaseConnection db;

	public OrderTransactionController(){
		db = new DatabaseConnection();
	}

	// To insert transaction detail into database and get the auto generate transaction id
	@SuppressWarnings("resource")
	public int insertTransaction(OrderTransaction orderTransaction) throws SQLException{
		
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		int status =0;
       
		String sql="INSERT INTO ordertransaction(TransactionDate,AmountCharged,TransactionStatus,Last4Digits,OrderMode)"+
                "VALUES (localtime(),?, ?, ?, ?);";

		try{
			conn = db.getConnection();
			ps = conn.prepareStatement(sql);
          
			ps.setFloat(2, orderTransaction.getAmountCharged());
			if (orderTransaction.isTransactionStatus())
				ps.setInt(3, 1);
            else
                 ps.setInt(3, 0);
            ps.setInt(4, orderTransaction.getLast4Digits());
            ps.setString(5,orderTransaction.getOrderMode());
            status = ps.executeUpdate();


            if(status!=0){   
            	
            	// To get the order transaction id generated by database
                sql = "SELECT * FROM ordertransaction";
        
                 ps = conn.prepareStatement(sql);
                 rs = ps.executeQuery();
                 // Move cursor to the last row of the table
                 rs.last();

                 orderTransaction.setOrderTransactionId(rs.getInt(1)); 

            }         

        }catch(Exception e){
        	e.printStackTrace();
        }
        finally{
            if (ps!= null)
                ps.close();
            if (rs!=null)
                rs.close();
            if(conn!=null)
                conn.close();       	
        }
        return orderTransaction.getOrderTransactionId();
	}
}
